### PR TITLE
Feat/versioned contract

### PR DESCRIPTION
**Pull request by neithanmo**
This adds support for versioned smart contract. see #153 

:link: [zboto Link](https://app.clickup.com/t/8693gmmg0)

### CODE REVIEW

**Comment by ftheirs** [comment]
Just two minor comments that will be required by Ledger, everything else looks good to me 💪 
- Remove please linker scripts: `app/script_*.ld`
- Add in the root ledger_app.toml and update guidelines_enforcer.yaml ([reference](https://github.com/Zondax/ledger-algorand/commit/cdeb034cf7b06dac5baed28c94e97bc3deb454ee))

**Comment by kyranjamie** [comment]
Hey @neithanmo. Did the ledger app not work on Stax? What's required to get Stax support?

**Comment by edgarkhanzadian** [comment]
@neithanmo can you, please, publish the package to npm with this fix?

**Comment by neithanmo** [comment]
> @neithanmo can you, please, publish the package to npm with this fix?

Current published version must work without any issue, changes have been done directly to the parser layer and does not required any updates to the npm package.

**Comment by edgarkhanzadian** [comment]
@neithanmo oh right! Should it be released to ledger store then? I think the latest version there is "v0.23.3"

**Pull request merged**
