### PR TITLE
Feat: Add support for arbitrary # of multisig signers

### PR DESCRIPTION
**Pull request by jbencin**
### Description

This PR aims to support Stacks multisig with an arbitrary number of signers. Current code only works for a max of 2 multisig signers

**UPDATE:** This PR now also adds support for a new SIP enabling non-sequential multisig transactions ([PR](https://github.com/stacksgov/sips/pull/152), [Document](https://github.com/jbencin/sips/blob/aef590f31ee6f237cddaf589cf8bc787e1ac7a06/sips/sip-02x/sip-02x-non-sequential-multisig-transactions.md))

### Current Status

- [x] Rust unit tests passing
- [x] C code compiles without warnings
- [x] ZEMU tests pass
- [x] Tested to run on Ledger
- [x] Tested and working m-of-n sequential multisig transactions
- [x] Tested and working m-of-n non-sequential multisig transactions

### Breaking Changes

- Do not use custom data format in `remainder` field while parsing transaction. Transactions should instead be updated with new signature after each signing round, as described in [SIP-005](https://github.com/stacksgov/sips/blob/main/sips/sip-005/sip-005-blocks-and-transactions.md#transaction-signing-and-verifying) (step 5 under "Transaction Signing and Verifying"). Wallet software will need to be updated to modify transaction accordingly.

### TODO / Limitations

- Currently iteration through multisig fields is `O(n^2)` due to having to parse the structure on each access. Need to figure out how to handle a variable length array in a `no_std` environment or limit to a max number of signers in order to use an `ArrayVec`. I have a branch where it parses a fixed number of `TransactionAuthField`s into an fixed-size `ArrayVec`, and keeps a reference to the start of the unparsed data (if any), so it can be parsed on-demand later, but currently tests are failing on it
- <del>As I can't figure out how to recover a pubkey from a ECDSA signature on a Ledger, the signatures of previous signers are not validated before signing.</del> This isn't really necessary
- 

:link: [zboto Link](https://app.clickup.com/t/8692j9hr8)

### CODE REVIEW

**Comment by neithanmo** [comment]
> As I can't figure out how to recover a ECDSA pubkey from a signature on a Ledger, the signatures of previous signers are not validated before signing

To verify previous signatures the process would be more complex, we would need the path, and the presig-hash previous signer used, 
compute the key and verify signature matches. that would make more complex the protocol, requiring maybe back-forward communication between the app and the host. 
That is why we use the remaining data as the postsig-hash of the previous signer, and use it as a presig-hash. 
also there is no need to update the transaction as just some fields of it are used to compute the presig-hash, updating as you propose would require again back and forward communication with the wallet or more unsafe operations in the buffer. The algorithm defines what fields and how to update them so it is better to use a separate buffer for this.

**Comment by kantai** [comment]
> That is why we use the remaining data as the postsig-hash of the previous signer, and use it as a presig-hash.
also there is no need to update the transaction as just some fields of it are used to compute the presig-hash, updating as you propose would require again back and forward communication with the wallet or more unsafe operations in the buffer. The algorithm defines what fields and how to update them so it is better to use a separate buffer for this.

It looks like this PR achieves the same thing as the previous approach, but uses the `TransactionAuth` field to compute the postsig-hash of the previous signer. The `TransactionAuth` field contents are well-defined by the transaction signing spec ([SIP-005](https://github.com/stacksgov/sips/blob/main/sips/sip-005/sip-005-blocks-and-transactions.md#transaction-signing-and-verifying)). This strategy also allows the app to work with an arbitrary number of signers, whereas the previous approach only worked with 2-of-n. Neither approach actually verifies the previous signer's signature, but as you say, that isn't possible without some back-and-forth communication. It also isn't necessary, because the hardware device is still verifying the transaction payload, and the non-signature `TransactionAuth` fields.

**Comment by jbencin** [comment]
> To verify previous signatures the process would be more complex, we would need the path, and the presig-hash previous signer used,

This could be done if we could recover the pubkeys from the signature on-device, but I don't think verifying the signatures is actually necessary. The current code does not do this, and if the signatures are not valid, the transaction will be rejected by the blockchain anyway. What **is** important is that we make sure we are signing the transaction that we think we are.

Because after the first signer, what gets signed is the previous signer's postsig-hash, and **not** the transaction itself. This means we need to know every previous postsig-hash in order to link our signature to the transaction, and to verify that we are not being tricked into signing something we don't want.

Technically, with the current scheme, we *could* generate a valid signature for a transaction with any number of multisig signers, but if we are limited to one postsig-hash, we can't actually link it to the transaction for n > 2 signers.  I had two options for how I could've modified the code to allow us to safely sign beyond n > 2 signers:
- Include the postsig-hash for all previous signers in `remainder`
- Include the previous signatures in the transaction itself, as described in SIP-005, and use them to compute the postsig-hashes

It's fairly simple to compute postsig-hash of previous signers if we have their signature, and either way would require modifications to the Hiro wallet code. So I chose the method laid out in SIP-005, which will have the added benefit of being interoperable with non-Ledger wallets

**Comment by jbencin** [comment]
> Could you please include Zemu tests with test vectors?

Will work on this. Is there a document describing how to do this, or some example in the repo I could start from?

> Given these breaking changes, how is backwards compatibility going to be ensured?

Here's what I expect the compatibility issues to be between different versions of wallet software and Ledger Stacks app:

- If users are not attempting to sign multisig transactions, then there should be no backwards compatibility issues at all
- If you are using multisig...
   - Users with a newer version of the Ledger app (≥0.24.x) would need to update wallet or multisig signing would fail
   - Users with an older version of the Ledger app (<0.24.x) should not experience breakage with newer version of wallet. The wallet can continue to pass data in `remainder` as it does now
   - There may be issues creating a transaction where some participants are using < 0.24.x and others using ≥ 0.24.x, depending on signing order and whether they are using an updated wallet or not
   - Because this follows the standard in SIP-005, it would possible to create a multisig transaction where some participants are using Ledger and others are using different wallets

I think the biggest issue would be if a new version of the wallet broke multisig for older versions of the Ledger app, but that shouldn't happen

Wallets should make the following changes:

- After recieving tx signature from Ledger, replace signer's pubkey in `TransactionAuthField`  with signer's signature
- May try and detect if a user with Ledger app < 0.24.x is trying to sign a multisig tx previously signed by user with ≥ 0.24.x. Signing in this order won't be possible AFAIK

I can work with the Hiro/Leather wallet team on this, but I don't know if there are other Stacks wallets out there that support multisig on Ledger right now

> Are you planning to address this issue in this PR before running an audit?

The pubkey recovery and signature validation could be nice to have, but it's not necessary to produce a valid signature and ensure that the user is not getting tricked into signing the wrong transaction. And if the signatures aren't valid, the tx will be rejected by the blockchain anyway

**Comment by fess-v** [comment]
Hey @jleni @neithanmo ! Just integrated this PR with [Asigna](https://asigna.io/) internally, really looking forward to making it live when this PR is merged. Tested this change in our project and it worked perfectly, making the dev environment available soon. Big support for Ledger multisig on Stacks!

**Comment by kyranjamie** [comment]
Thanks for the PR @jbencin. Look forward to getting this integrated in Leather.

**Comment by fess-v** [comment]
Hey @neithanmo @jleni ! is there anything else blocking this PR? Thanks a lot in advance, really waiting for it.

**Comment by neithanmo** [comment]
Hi @fess-v 
There were some changes in main branch, can you rebase?

**Comment by jbencin** [comment]
Hey @neithanmo I rebased this onto the latest `main`. Right now there's only one minor issue that I'm aware of:

- 3 of the `make zemu_tests` tests fail because the app version screenshots don't match (`v0.23.11` vs. `v0.24.0`)
 
Let me know if you're okay with upping the minor version to `24`, and I'll take new screenshots with Speculos. Also let me know if there is anything else needed in order to merge (more tests, code formatting, etc.)

**Comment by jbencin** [comment]
I've fixed the `make zemu_test` target by updating the screenshots, so all of those tests are passing now, and the tests further down the pipeline should run next time CI is triggered

The other step that is failing in CI is "Clang Static Analyzer", but the errors are in parts of the code not modified by this PR, and this step also fails on other PRs, so I assume it's not an issue

@neithanmo can you trigger another CI run?

**Comment by neithanmo** [comment]
@jbencin i looked at the issues reported by CI I will push some changes into your branch to fix them asap. thanks for the work on this.

**Comment by fess-v** [comment]
Hey guys @neithanmo @jleni is there anything else to be done to move forward? Thanks a lot, really appreciate your work

**Comment by neithanmo** [comment]
@jbencin to fix the last CI issue. First update deps/ledger-zxlib to tag V20.0.0
commit and push it so we can run CI jobs again.

**Comment by jbencin** [comment]
> @jbencin First update deps/ledger-zxlib to tag V20.0.0 commit and push it so we can run CI jobs again

I tried this and now `make zemu_test` fails:

```
Test Suites: 2 failed, 2 total
Tests:       38 failed, 19 passed, 57 total
Snapshots:   0 total
Time:        411.543 s
Ran all test suites.
[ZEMU] Stopped
[ZEMU] Removed
error Command failed with exit code 1.
```

Also tried the tags `v21.1.3` and `v22.0.1`, which both fail to compile

**Comment by fess-v** [comment]
Heey @neithanmo could you help with the fixes above? thanks!

**Comment by jbencin** [comment]
Hey @neithanmo we have merged @fess-v's PR stacks-network/stacks-core#3710 which allows for order-independent multisig. This will be activated upon Epoch 3.0 (in the next couple months). Since this PR also adds support for order-independent multisig on the Ledger side, and we expect that's what everyone will want to use going forward, it's important to get this merged so that Ledger users can participate in the new type of multisig transactions

I don't know what's going on with the failing CI and deps/ledger-zxlib, but as far as I can tell, the same CI steps are failing on `main`. If this is the case, these failures shouldn't hold up a merge

**Comment by neithanmo** [comment]
@jbencin in the current status check list:
` Tested and working m-of-n non-sequential multisig transactions` is missing. Do you plan to include it in this PR?

**Comment by jbencin** [comment]
@neithanmo Added test for order-independent multisig in `standard.test.ts` and verified that it produces valid signatures (both in the unit test, and using `stacks-inspect decode-tx` to check against blockchain code).

This PR is ready to merge now!

**Comment by neithanmo** [comment]
> @neithanmo Added test for order-independent multisig in `standard.test.ts` and verified that it produces valid signatures (both in the unit test, and using `stacks-inspect decode-tx` to check against blockchain code).
> 
> This PR is ready to merge now!

Waiting for CI to run.
there would be some errors tho, we would need to fix the codeQL reports

**Comment by jbencin** [comment]
CI is still failing, but the same steps fail on `main` also:

image

I don't know what's causing it, but I don't think it makes sense to try and fix the CI in this PR, since it didn't break here. It would make more sense to fix it in a separate PR

**Pull request merged**
